### ISSUE TITLE
jdf安装不成功

### ISSUE THREAD

**Issue by landy2014** [putaoshu/jdf#12]
如图：
![image](https://cloud.githubusercontent.com/assets/6982058/7172157/6495d028-e415-11e4-8b3c-03977761118b.png)
![image](https://cloud.githubusercontent.com/assets/6982058/7172163/6e18954a-e415-11e4-93b7-73d216ead686.png)

请不吝赐教，谢谢

**Comment by chenxiaochun** [comment]
你好，出现这个问题是因为jdf对最新版的nodejs兼容性不太好。
你安装此地址：http://nodejs.org/dist/v0.10.35/中的node-v0.10.35-x86.msi 即可，谢谢。

**Comment by landy2014** [comment]
谢谢。

**Comment by wshxbqq** [comment]
似乎你本地机器没有  python ？


在 2015年4月16日 上午8:49，landy2014 <notifications@github.com>写道：
