### ISSUE TITLE
csssprite中配置项imagesSuffix设置为添加时间戳的功能没有。

### ISSUE THREAD

**Issue by changxiao** [putaoshu/jdf#14]
"imagesSuffix"配置项设置为1和2的时候无效
/*
0：不添加任何后缀
 1：给css中需要cssSprite的背景图添加后缀，后缀会被添加在文件扩展名的后面。例如：test.png => test.png?20150319161000
 2：给css中需要cssSprite的背景图添加后缀，后缀会被添加在文件名的后面，生成一个新的文件。例如：test.png => test20150319161000.png
*/

**Comment by chenxiaochun** [comment]
好的，我看看

**Comment by chenxiaochun** [comment]
已经解决了，稍后会更新版本的。

**Comment by changxiao** [comment]
NB
