### ISSUE TITLE
最新版的  背景图合并的路径

### ISSUE THREAD

**Issue by llqfront** [putaoshu/jdf#17]
合并背景的路径希望能得到解决
要不 生成后还得重新再去改一次路径   很不方便

另外有个小问题

就是 如果有不同的scss 文件    比如果 index.scss    然后又import test.scss  生成的背景图会有两份 并且有重复    这个不知道如何 避免

**Comment by chenxiaochun** [comment]
第一个问题你加上`"cssImagesUrlReplace": true`还是不能解决吗。
第二个问题目前不太好处理，因为jdf的背景合并是以文件为单元去合并的。

**Comment by llqfront** [comment]
cssImagesUrlReplace": true 无法解决 反而回再增加一层
