### ISSUE TITLE
commonjs的问题

### ISSUE THREAD

**Issue by dante1977** [putaoshu/jdf#26]
jdf 已经是一个构建工具了，为什么不用commonjs的规范来写js，然后在构建过程中把依赖分析好，这样，对于在线上运行时，就可以省掉依赖分析这个步骤，也不用seajs等前端的模块化框架了。

**Comment by chenxiaochun** [comment]
能再详细说一下您的建议吗？

**Comment by putaoshu** [comment]
@dante1977  是说支持要commonjs规范的JS文件打包?

**Comment by dante1977** [comment]
对，就是这个意思，类似webpack等工具的功能。

**Comment by putaoshu** [comment]
@chenxiaochun 看看，能否支持下commonjs规范的JS文件打包

**Comment by chenxiaochun** [comment]
呃，可以试试
