### ISSUE TITLE
字体文件eot ttf等会被过滤 不能上传到服务器

### ISSUE THREAD

**Issue by eijil** [putaoshu/jdf#34]
jdf u 的时候字体文件不能被上传到服务器
编译以下代码的时候第二个src不会被加上绝对路径

@font-face {
  font-family: 'iconfont';
  src: url(/css/i/iconfont.eot); /* IE9*/
  src: url(/css/i/iconfont.eot?#iefix) format('embedded-opentype'), /* IE6-IE8 */
  url(/css/i/iconfont.woff) format('woff'), /* chrome、firefox */
  url(/css/i/iconfont.ttf) format('truetype'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/
  url(/css/i/iconfont.svg#iconfont) format('svg'); /* iOS 4.1- */
}

**Comment by chenxiaochun** [comment]
目前jdf确实是不支持对iconfont的路径处理，这问题我得研究一下。。。

**Comment by chenxiaochun** [comment]
现在已经支持icon font了，更新新版本即可jdf@2.0.2
